name: CICD Pipeline MF App

on:
  push:
    branches:
      - main

jobs:
  backend-ci:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Ruff
        run: ruff check app tests

      - name: Run Pytest
        run: python -m pytest
    
# Frontend CI Tests
  frontend-ci:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check frontend application
        run: node --check server.js

#Build and push Docker images for backend and frontend
  docker-build-push:
    runs-on: self-hosted

    needs:
      - backend-ci
      - frontend-ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
# For Self-hosted runners,  Installed Docker Buildx in advance.
# so no need to set up Buildx explicitly. Uncomment the following lines 
# if you want to set up Buildx explicitly on github acitions runner.

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v4

      - name: Build and push backend image
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: manishgokhare/mf-tracker-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: manishgokhare/mf-tracker-frontend:latest
  
  # Deploy to EC2 instance (Amazon Linux).
  deploy-to-ec2:
    runs-on: self-hosted

    needs:
      - docker-build-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key

      
      - name: Copy deployment files to EC2
        run: |
          scp \
              -i ~/.ssh/ec2_key \
              -o StrictHostKeyChecking=no \
              docker-compose.yml \
              ${{ vars.EC2_USER }}@${{ vars.EC2_HOST }}:/opt/mf-tracker/

          scp \
              -i ~/.ssh/ec2_key \
              -o StrictHostKeyChecking=no \
              database/init.sql \
              ${{ vars.EC2_USER }}@${{ vars.EC2_HOST }}:/opt/mf-tracker/database/        

      - name: Deploy application
        run: |
          ssh \
            -i ~/.ssh/ec2_key \
            -o StrictHostKeyChecking=no \
            ${{ vars.EC2_USER }}@${{ vars.EC2_HOST }} << 'EOF'

            set -e

            cd /opt/mf-tracker

            echo "Pulling latest Docker images..."
            docker compose pull

            echo "Starting application..."
            docker compose up -d

            echo "Deployment status:"
            docker compose ps

          EOF